// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class NoOpEvent implements flatbuffers.IUnpackableObject<NoOpEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NoOpEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNoOpEvent(bb:flatbuffers.ByteBuffer, obj?:NoOpEvent):NoOpEvent {
  return (obj || new NoOpEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNoOpEvent(bb:flatbuffers.ByteBuffer, obj?:NoOpEvent):NoOpEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NoOpEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startNoOpEvent(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endNoOpEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNoOpEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  NoOpEvent.startNoOpEvent(builder);
  return NoOpEvent.endNoOpEvent(builder);
}

unpack(): NoOpEventT {
  return new NoOpEventT();
}


unpackTo(_o: NoOpEventT): void {}
}

export class NoOpEventT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return NoOpEvent.createNoOpEvent(builder);
}
}
