// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ServerStatRequest implements flatbuffers.IUnpackableObject<ServerStatRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerStatRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsServerStatRequest(bb:flatbuffers.ByteBuffer, obj?:ServerStatRequest):ServerStatRequest {
  return (obj || new ServerStatRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsServerStatRequest(bb:flatbuffers.ByteBuffer, obj?:ServerStatRequest):ServerStatRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerStatRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startServerStatRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endServerStatRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createServerStatRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  ServerStatRequest.startServerStatRequest(builder);
  return ServerStatRequest.endServerStatRequest(builder);
}

unpack(): ServerStatRequestT {
  return new ServerStatRequestT();
}


unpackTo(_o: ServerStatRequestT): void {}
}

export class ServerStatRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ServerStatRequest.createServerStatRequest(builder);
}
}
