[package]
name = "st_commander_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
darling = "0.20"
syn = { version = "2.0", default-features = false, features = ["parsing"] }
to_snake_case = "0.1"
toml = "0.8"
