// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Vec2, Vec2T } from '../shared/vec2.js';
import { UnitState } from '../unit/unit-state.js';


export class Unit implements flatbuffers.IUnpackableObject<UnitT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Unit {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnit(bb:flatbuffers.ByteBuffer, obj?:Unit):Unit {
  return (obj || new Unit()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnit(bb:flatbuffers.ByteBuffer, obj?:Unit):Unit {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Unit()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

controlledBy():string|null
controlledBy(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
controlledBy(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

state():UnitState {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : UnitState.Idle;
}

position(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startUnit(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addControlledBy(builder:flatbuffers.Builder, controlledByOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, controlledByOffset, 0);
}

static addState(builder:flatbuffers.Builder, state:UnitState) {
  builder.addFieldInt8(3, state, UnitState.Idle);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, positionOffset, 0);
}

static endUnit(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishUnitBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedUnitBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}


unpack(): UnitT {
  return new UnitT(
    this.id(),
    this.name(),
    this.controlledBy(),
    this.state(),
    (this.position() !== null ? this.position()!.unpack() : null)
  );
}


unpackTo(_o: UnitT): void {
  _o.id = this.id();
  _o.name = this.name();
  _o.controlledBy = this.controlledBy();
  _o.state = this.state();
  _o.position = (this.position() !== null ? this.position()!.unpack() : null);
}
}

export class UnitT implements flatbuffers.IGeneratedObject {
constructor(
  public id: number = 0,
  public name: string|Uint8Array|null = null,
  public controlledBy: string|Uint8Array|null = null,
  public state: UnitState = UnitState.Idle,
  public position: Vec2T|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const controlledBy = (this.controlledBy !== null ? builder.createString(this.controlledBy!) : 0);

  Unit.startUnit(builder);
  Unit.addId(builder, this.id);
  Unit.addName(builder, name);
  Unit.addControlledBy(builder, controlledBy);
  Unit.addState(builder, this.state);
  Unit.addPosition(builder, (this.position !== null ? this.position!.pack(builder) : 0));

  return Unit.endUnit(builder);
}
}
