[package]
name = "st_commander_sdk"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
to_snake_case.workspace = true

anyhow = "1.0"

serde.workspace = true
serde_json.workspace = true

utoipa.workspace = true
