[package]
name = "st_crew_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

schemars = { version = "0.8", optional = true }

[dev-dependencies]
serde_json = "1.0"
